# basic options
title: My Awesome blog
author: Charlotte Friis Theisen
email: your-email@domain.com
description: On ths site I will post cool updates
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
